#
# This file is part of the PocketSVG package.
#
# Copyright (c) Ponderwell, Ariel Elkin, Fjölnir Ásgeirsson, and Contributors
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

name: CI

on:
  push:
    branches: [master]
    tags:
      - '*' # run on every tag
  pull_request:

jobs:
  primary:
    name: Primary
    runs-on: macOS-13
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build demos
        run: sh ci/build_demos.sh

      - name: Run unit tests
        run: sh ci/test.sh

  spm:
    name: Swift Package Manager
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - name: Swift Build
        run: swift build

  cocoapods:
    name: Cocoapods
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - name: Lint Podspec
        run: pod lib lint --allow-warnings
